on: [push]
jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: '3.8'
          - python: '3.12'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - run: python3 -m pip install ruff
    - name: lint
      run: ruff check
    - name: test
      run: python3 -m unittest
